
import os

replacements = {
    'da\ufffdo': 'daño',
    'Da\ufffdo': 'Daño',
    'm\ufffds': 'más',
    'Duraci\ufffdn': 'Duración',
    'cr\ufffdtico': 'crítico',
    'formaci\ufffdn': 'formación',
    'confusi\ufffdn': 'confusión',
    'carmes\ufffd': 'carmesí',
    'reducci\ufffdn': 'reducción',
    'r\ufffdpido': 'rápido',
    'Cr\ufffdtico': 'Crítico',
    'despu\ufffds': 'después',
    'Part\ufffdculas': 'Partículas',
    'Atracci\ufffdn': 'Atracción',
    'Formaci\ufffdn': 'Formación',
    '\ufffdguila': 'Águila',
    'Vac\ufffdo': 'Vacío',
    'Drag\ufffdn': 'Dragón',
    'Term\ufffdpilas': 'Termópilas',
    'T\ufffdxico': 'Tóxico',
    'detr\ufffds': 'detrás',
    'da\ufffda': 'daña',
    'precisi\ufffdn': 'precisión',
    'a\ufffdos': 'años',
    'HIST\ufffdRICAS': 'HISTÓRICAS',
    'l\ufffdnea': 'línea',
    'Centuri\ufffdn': 'Centurión',
    'Bendici\ufffdn': 'Bendición',
    'E\ufffdlica': 'Eólica',
    'R\ufffdfaga': 'Ráfaga',
    'Apocal\ufffdptica': 'Apocalíptica',
    'l\ufffdser': 'láser',
    'est\ufffdtico': 'estático',
    'Sombr\ufffdas': 'Sombrías',
    'Legi\ufffdn': 'Legión',
    'S\ufffdmbolos': 'Símbolos',
    '\ufffdter': 'Éter',
    'R\ufffdpido': 'Rápido',
    'est\ufffd': 'está',
    'maestr\ufffda': 'maestría',
    'desaf\ufffdo': 'desafío',
    'r\ufffdpidas': 'rápidas',
    'esp\ufffdritu': 'espíritu',
    '\ufffdAROO!': '¡AROO!',
    'Versi\ufffdn': 'Versión',
    'Presi\ufffdn': 'Presión',
    'Atmosf\ufffdrica': 'Atmosférica',
    'Sat\ufffdlite': 'Satélite',
    'Se\ufffdor': 'Señor',
    'Explosi\ufffdn': 'Explosión',
    'L\ufffdnea': 'Línea',
    'Drac\ufffdnica': 'Dracónica',
    'M\ufffdximo': 'Máximo',
    't\ufffdxicas': 'tóxicas',
    'informaci\ufffdn': 'información',
    'Frenes\ufffd': 'Frenesí',
    'MISI\ufffdN': 'MISIÓN',
    'atracci\ufffdn': 'atracción',
    'INFORMACI\ufffdN': 'INFORMACIÓN',
    't\ufffdxico': 'tóxico',
    'Animaci\ufffdn': 'Animación',
    'Flam\ufffdgera': 'Flamígera',
    'ESTAD\ufffdSTICAS': 'ESTADÍSTICAS',
    'est\ufffdn': 'están',
    'Regeneraci\ufffdn': 'Regeneración',
    'f\ufffdsica': 'física',
    'm\ufffdgico': 'mágico',
    'seg\ufffdn': 'según',
    'Cicl\ufffdn': 'Ciclón',
    'presi\ufffdn': 'presión',
    'desaf\ufffdos': 'desafíos',
    'energ\ufffda': 'energía',
    'm\ufffdltiple': 'múltiple',
    'Rel\ufffdmpagos': 'Relámpagos',
    'Prisi\ufffdn': 'Prisión',
    'Maestr\ufffda': 'Maestría',
    'S\ufffdmbolo': 'Símbolo',
    's\ufffdsmicas': 'sísmicas',
    '\ufffdJugador': '¡Jugador',
    'S\ufffdSMICO': 'SÍSMICO',
    'T\ufffdtulo': 'Título',
    'TERM\ufffdPILAS': 'TERMÓPILAS',
    'Subt\ufffdtulo': 'Subtítulo',
    'LEGI\ufffdN': 'LEGIÓN',
    'CR\ufffdTICO': 'CRÍTICO',
    'atr\ufffds': 'atrás',
    'part\ufffdculas': 'partículas',
    'Despu\ufffds': 'Después',
    'REDISE\ufffdADO': 'REDISEÑADO',
    'dif\ufffdciles': 'difíciles',
    'curaci\ufffdn': 'curación',
    '\ufffdpico': 'Épico',
    '\ufffdlite': 'Élite',
    'Ca\ufffd\ufffdn': 'Cañón',
    'Ca\ufffdn': 'Cañón',
    'CENTURI\ufffdN': 'CENTURIÓN',
    'MALDICI\ufffdN': 'MALDICIÓN',
    'Maldici\ufffdn': 'Maldición',
    '\ufffdEl': '¡El',
    'reduc\ufffda': 'reducía',
    'Navegaci\ufffdn': 'Navegación',
    'cr\ufffdticos': 'críticos',
    'ACTUALIZACI\ufffdN': 'ACTUALIZACIÓN',
    'M\ufffdS': 'MÁS',
    'Redise\ufffdos': 'Rediseños',
    'redise\ufffdado': 'rediseñado',
    'Evasi\ufffdn': 'Evasión',
    'Radiaci\ufffdn': 'Radiación',
    'est\ufffds': 'estás',
    'Descripci\ufffdn': 'Descripción',
    'Organizaci\ufffdn': 'Organización',
    'segu\ufffda': 'seguía',
    'CORRECCI\ufffdN': 'CORRECCIÓN',
    'ten\ufffda': 'tenía',
    'Hac\ufffda': 'Hacía',
    'pr\ufffdximos': 'próximos',
    'Filosof\ufffda': 'Filosofía',
    'M\ufffds': 'Más',
    'diversi\ufffdn': 'diversión',
    'C\ufffdmo': 'Cómo',
    'cu\ufffdntos': 'cuántos',
    'estrat\ufffdgicamente': 'estratégicamente',
    'categor\ufffdas': 'categorías',
    'estrat\ufffdgico': 'estratégico',
    'CARACTER\ufffdSTICAS': 'CARACTERÍSTICAS',
    'combinaci\ufffdn': 'combinación',
    'infracci\ufffdn': 'infracción',
    'Cret\ufffdceo': 'Cretáceo',
    'monta\ufffdas': 'montañas',
    'Especializaci\ufffdn': 'Especialización',
    'f\ufffdsico': 'físico',
    'C\ufffdsmica': 'Cósmica',
    'Andr\ufffdmeda': 'Andrómeda',
    'coraz\ufffdn': 'corazón',
    'vers\ufffdtiles': 'versátiles',
    'c\ufffdsmica': 'cósmica',
    'evasi\ufffdn': 'evasión',
    'fr\ufffdgil': 'frágil',
    'F\ufffdnix': 'Fénix',
    'Volc\ufffdn': 'Volcán',
    'ca\ufffcda': 'caída',
    'ca\ufffda': 'caída',
    'sabidur\ufffda': 'sabiduría',
    'Monta\ufffdas': 'Montañas',
    'determinaci\ufffdn': 'determinación',
    'protecci\ufffdn': 'protección',
    'centuri\ufffdn': 'centurión',
    'otorg\ufffdndote': 'otorgándote',
    'da\ufffdan': 'dañan',
    'c\ufffddigo': 'código',
    'Guardi\ufffdn': 'Guardián',
    'r\ufffdpidamente': 'rápidamente',
    'instant\ufffdneamente': 'instantáneamente',
    'dem\ufffds': 'demás',
    'radiaci\ufffdn': 'radiación',
    'cicl\ufffdn': 'ciclón',
    'da\ufffdando': 'dañando',
    'pr\ufffdximo': 'próximo',
    'recibir\ufffdn': 'recibirán',
    'm\ufffdltiples': 'múltiples',
    'vac\ufffdo': 'vacío',
    'est\ufffdtica': 'estática',
    'v\ufffdctima': 'víctima',
    'apocal\ufffdptica': 'apocalíptica',
    'Tecnolog\ufffda': 'Tecnología',
    'explosi\ufffdn': 'explosión',
    'l\ufffdseres': 'láseres',
    'Supremac\ufffda': 'Supremacía',
    'Cibern\ufffdtica': 'Cibernética',
    'tecnolog\ufffda': 'tecnología',
    'visi\ufffdn': 'visión',
    'el\ufffdctrico': 'eléctrico',
    'Penetraci\ufffdn': 'Penetración',
    'Reducci\ufffdn': 'Reducción',
    'inmovilizaci\ufffdn': 'inmovilización',
    'Confusi\ufffdn': 'Confusión',
    'Gesti\ufffdn': 'Gestión',
    'T\ufffdrmica': 'Térmica',
    'Tecnol\ufffdgica': 'Tecnológica',
    'tecnol\ufffdgico': 'tecnológico',
    'm\ufffdximo': 'máximo',
    'descripci\ufffdn': 'descripción',
    'MAESTR\ufffdA': 'MAESTRÍA',
    'Misi\ufffdn': 'Misión',
    'bendici\ufffdn': 'bendición',
    'rect\ufffdngulo': 'rectángulo',
    'l\ufffdneas': 'líneas',
    'Transformaci\ufffdn': 'Transformación',
    '\ufffdpica': 'Épica',
    'C\ufffdsar': 'César',
    'Le\ufffdnidas': 'Leónidas',
    'P\ufffdrpura': 'Púrpura',
    'm\ufffdstico': 'místico',
    'G\ufffdlem': 'Gólem',
    'atraves\ufffd': 'atravesó',
    '\ufffdExplosi\ufffdn': '¡Explosión',
    'DESTRUCCI\ufffdN': 'DESTRUCCIÓN',
    '\ufffdLLUVIA': '¡LLUVIA',
    '\ufffdCIDA!': 'ÁCIDA!',
    '\ufffdGOLPE': '¡GOLPE',
    'desliz\ufffdndose': 'deslizándose',
    'SUBTERR\ufffdNEO': 'SUBTERRÁNEO',
    '\ufffdENVENENAMIENTO': '¡ENVENENAMIENTO',
    's\ufffdmbolos': 'símbolos',
    'vibraci\ufffdn': 'vibración',
    '\ufffdpicos': 'Épicos',
    'variaci\ufffdn': 'variación',
    'patr\ufffdn': 'patrón',
    'detonaci\ufffdn': 'detonación',
    'FORMACI\ufffdN': 'FORMACIÓN',
    'Marr\ufffdn': 'Marrón',
    '\ufffdPor': '¿Por',
    'Pr\ufffdximo': 'Próximo',
    'M\ufffdXIMA': 'MÁXIMA',
    'OPTIMIZACI\ufffdN': 'OPTIMIZACIÓN',
    '\ufffdGloria': '¡Gloria',
    'direcci\ufffdn': 'dirección',
    'Direcci\ufffdn': 'Dirección',
    'posici\ufffdn': 'posición',
    'Da\ufffdar': 'Dañar',
    'r\ufffdpida': 'rápida',
    'Intimidaci\ufffdn': 'Intimidación',
    'BENDICI\ufffdN': 'BENDICIÓN',
    'Curaci\ufffdn': 'Curación',
    's\ufffdmbolo': 'símbolo',
    'TERM\ufffdPILAS!': 'TERMÓPILAS!',
    'CONFIGURACI\ufffdN': 'CONFIGURACIÓN',
    'Presi\ufffdn': 'Presión',
    # Single characters at the end of matches that missed context
    '\ufffd': 'í', # Risky, but common
}

try:
    with open('index.html', 'r', encoding='utf-8', errors='replace') as f:
        content = f.read()

    print(f"Content length: {len(content)}")
    if '\ufffd' in content:
        print("Found corruption character in content.")
        match_count = content.count('\ufffd')
        print(f"Count of corruption char: {match_count}")
    else:
        print("Did NOT find corruption character in content.")

    new_content = content
    count = 0
    
    # Sort keys by length descending to replace longer words first
    sorted_keys = sorted(replacements.keys(), key=len, reverse=True)
    
    for key in sorted_keys:
        val = replacements[key]
        if key in new_content:
            c = new_content.count(key)
            new_content = new_content.replace(key, val)
            # safe_key = key.replace('\ufffd', '?')
            # print(f"Replaced {c} occurrences of '{safe_key}' -> '{val}'")
            pass

    # Second pass for common single replacements that are safe in context
    # ? -> ñ in "Da?o" was handled.
    # ? -> í in "s?smico"
    
    # Generic replacements for remaining patterns
    generic_replacements = [
        ('?n', 'ón'),
        ('?a', 'ía'),
        ('?o', 'ño'), # Guessing
    ]
    
    # We won't do unsafe generic replacements.
    
    with open('index.html', 'w', encoding='utf-8') as f:
        f.write(new_content)
        
    print(f"Total replacements: {count}")

except Exception as e:
    print(f"Error: {e}")
